<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8381" started-at="2016-09-15T07:19:53Z" finished-at="2016-09-15T07:20:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8381" started-at="2016-09-15T07:19:53Z" finished-at="2016-09-15T07:20:02Z">
      <class name="Aserting">
        <test-method status="PASS" signature="load_url()[pri:0, instance:Aserting@34ce8af7]" name="load_url" is-config="true" duration-ms="8258" started-at="2016-09-15T12:49:53Z" finished-at="2016-09-15T12:50:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- load_url -->
        <test-method status="FAIL" signature="asserttrue1()[pri:0, instance:Aserting@34ce8af7]" name="asserttrue1" duration-ms="43" started-at="2016-09-15T12:50:01Z" finished-at="2016-09-15T12:50:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Aserting.asserttrue1(Aserting.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asserttrue1 -->
        <test-method status="PASS" signature="asserttrue2()[pri:0, instance:Aserting@34ce8af7]" name="asserttrue2" duration-ms="48" started-at="2016-09-15T12:50:02Z" finished-at="2016-09-15T12:50:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asserttrue2 -->
      </class> <!-- Aserting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
